<?php

/**
 * @file
 * Contains corplite_published_releases_feed.module.
 */

use Drupal\corplite_published_releases_feed\Entity\PublishedReleases;

/**
 * Cron callback function to run feed.
 */
function corplite_published_releases_feed_import() {
  \Drupal::logger('corplite_published_releases_feed')->notice("Called feed import successfully");
  $data = fetch_feed();
  \Drupal::logger('corplite_published_releases_feed')->notice("Imported " . count($data));
  foreach ($data as $feed_item) {
    $release = PublishedReleases::Load($feed_item['id']);
    if (!empty($release)) {
      // Published release exists, see if we need to update it.
      if (strtotime($feed_item['updated']) > $release->updated->getString()) {
        // Update the published release.
        \Drupal::logger('corplite_published_releases_feed')->notice("Updating id " . $feed_item['id'] ." as has changed");
        update_release_object($release, $feed_item);
      } else {
        // Published release has not changed, do nothing.
        \Drupal::logger('corplite_published_releases_feed')->notice("Skipped id " . $feed_item['id'] ." as has not changed");
      }
    } else {
      // Published release does not exist in the database, so store it.
      $release = PublishedReleases::create(['id' => $feed_item['id']]);
      update_release_object($release, $feed_item);
      \Drupal::logger('corplite_published_releases_feed')->notice("Stored id " . $feed_item['id'] ." in database");
    }
  }
  \Drupal::logger('corplite_published_releases_feed')->notice("Finished feed import successfully");
}

/**
 * Update the release object.
 */
function update_release_object($release, $feed_item) {
  $release->set('title', $feed_item['title']);
  $release->set('summary', $feed_item['summary']);
  $release->set('url', $feed_item['url']);
  $release->set('release_date', strtotime($feed_item['release_date']));
  $release->set('updated', strtotime($feed_item['updated']));
  $release->save();
}

/**
 * Retrieve the JSON feed.
 */
function fetch_feed() {
  $data = NULL;
  $client = \Drupal::service('http_client');
  $config = \Drupal::config('corplite_published_releases_feed.settings');
  $url = $config->get('data_source_url');

  try {
    $response = $client->get($url);

    if ($response->getStatusCode() == 200) {
      //$feed_contents = $response->getBody()->getContents();
      $feed_contents = json_decode(dummy_feed());

      $data = [];
      foreach ($feed_contents->entries as $row) {
        $data[] = [
          'id' => (integer) $row->id,
          'title' => (string) $row->title,
          'summary' => (string) $row->summary,
          'url' => (string) $row->url,
          'release_date' => (string) $row->release_date,
          'updated' => (string) $row->updated,
        ];
      }
    }
  }
  catch (Exception $e) {
    \Drupal::logger('corplite_published_releases_feed')->error($e);
  }
  return $data;
}

function dummy_feed() {
  return '{
      "name": "nisra release calendar",
      "updated": "2024-06-26T08:30:06Z",
      "entries": [
          {
              "id": "2025012901",
              "title": "Digital Skills in Northern Ireland 2023/24",
              "summary": "",
              "url": "",
              "release_date": "2025-01-29T09:30:00Z",
              "updated": "2024-12-03T10:31:00Z"
          },
          {
              "id": "2025010301",
              "title": "Deaths Registered in Northern Ireland - Week ending 27 December 2024",
              "summary": "",
              "url": "https://www.nisra.gov.uk/statistics/death-statistics/weekly-death-registrations-northern-ireland",
              "release_date": "2025-01-03T09:30:00Z",
              "updated": "2025-01-03T09:31:00Z"
          },
  {
    "id": "2024122002",
              "title": "Police recorded injury road traffic collisions and casualties Northern Ireland monthly report to 31 October 2024",
              "summary": "",
              "url": "https://www.psni.police.uk/about-us/our-publications-and-reports/official-statistics/road-traffic-collision-statistics",
              "release_date": "2024-12-20T09:30:00Z",
              "updated": "2024-12-21T00:30:06Z"
          },
  {
    "id": "2024122001",
              "title": "DVA Monthly Tests Conducted Statistics: November 2024",
              "summary": "",
              "url": "https://packages.drupal.org/8",
              "release_date": "2024-12-20T09:30:06Z",
              "updated": "2024-12-20T10:30:08Z"
          }
  ]
  }';
}
