<?php

/**
 * @file
 * Search related overrides and preprocessing.
 */

use Drupal\facets_summary\Entity\FacetsSummary;

/**
 * Implements hook_views_data_alter().
 */
function corplite_search_views_data_alter(array &$data) {
  $data['views']['search_sort_by'] = [
    'title' => t('Search sort links'),
    'help' => t('Provides links to sort search results by publication date and by relevance.'),
    'area' => [
      'id' => 'search_sort_by',
    ],
  ];
  return $data;
}

/**
 * Implements hook_preprocess_facets_summary_item_list().
 */
function corplite_search_preprocess_facets_summary_item_list(&$variables) {
  /* @var \Drupal\facets_summary\Entity\FacetsSummary $summary_facet */
  $summary_facet = \Drupal::entityTypeManager()->getStorage('facets_summary')->load($variables['facet_summary_id']);

  // Add the facet summary label as a facet description to allow us to
  // display that instead of the default facet (machine) name.
  if ($summary_facet instanceof FacetsSummary) {
    $facets = $summary_facet->getFacets();
    $summaries = [];
    foreach ($variables['items'] as $index => $item) {
      $label = $facets[$item['#title']['#facet']->id()]['label'];
      $variables['items'][$index]['#title']['#facet']->set('description', $label);

      $summaries[$label][] = $variables['items'][$index];
    }
    $variables['summaries'] = $summaries;
  }
}
