<?php

/**
 * @file
 * Search related overrides and preprocessing.
 */

use Drupal\Core\Url;
use Drupal\facets_summary\Entity\FacetsSummary;

/**
 * Implements hook_views_data_alter().
 */
function corplite_search_views_data_alter(array &$data) {
  $data['views']['search_sort_by'] = [
    'title' => t('Search sort links'),
    'help' => t('Provides links to sort search results by publication date and by relevance.'),
    'area' => [
      'id' => 'search_sort_by',
    ],
  ];
  return $data;
}

/**
 * Implements hook_preprocess_facets_summary_item_list().
 */
function corplite_search_preprocess_facets_summary_item_list(&$variables) {
  /* @var \Drupal\facets_summary\Entity\FacetsSummary $summary_facet */
  $summary_facet = \Drupal::entityTypeManager()->getStorage('facets_summary')->load($variables['facet_summary_id']);

  // Add the facet summary label as a facet description to allow us to
  // display that instead of the default facet (machine) name.
  if ($summary_facet instanceof FacetsSummary) {
    $facets = $summary_facet->getFacets();
    $summaries = [];
    foreach ($variables['items'] as $index => $item) {
      $id = $item['value']['#title']['#facet']->id();
      $label = $facets[$id]['label'];
      $variables['items'][$index]['value']['#title']['#facet']->set('description', $label);
      $summary_array = $variables['items'][$index]['value'];
      if (is_array($variables['items'][$index]['attributes'])) {
        $summary_array['attributes'] = $variables['items'][$index]['attributes'];
      }
      $summaries[$label][] = $summary_array;
    }
    $variables['summaries'] = $summaries;
  }
}

/**
 * Implements hook_preprocess_facets_item_list().
 */
function corplite_search_preprocess_facets_item_list(array &$variables) {
  // Early return if no items to process.
  if (empty($variables['items'])) {
    return;
  }

  // Alter links so that they are not treated as self-referential links
  // and, to help prevent bots following the links, output a data-href
  // instead of href which JS will then convert to a href on page load.

  // Attach library which converts link data-href to href.
  $variables['#attached']['library'][] = 'corplite_search/data_facet_href';
  foreach ($variables['items'] as $index => &$item) {

    /** @var \Drupal\Core\Url $url */
    $url = $variables['items'][$index]['#url'];
    $options = $url->getOptions();

    // Get the original href (URL) from the Url object.
    $original_href = $url->toString();

    // Set the 'data-href' attribute to the original href.
    $options['attributes']['data-facet-href'] = $original_href;

    // Set attribute to prevent link being treated as self-referential.
    $options['attributes']['data-self-ref'] = 'false';

    // Discard the query string from options if it's set.
    if (isset($options['query'])) {
      unset($options['query']);
    }

    // Rebuild the URL object to have href pointing at an anchor.
    $new_url = Url::fromUserInput('#main-content', $options);

    // Replace the facet link URL with the new one.
    $variables['items'][$index]['#url'] = $new_url;
  }
}
