_core:
  default_config_hash: 6Ka3T1c-CIjEUO1Q64NXKksLthkMhj53a6zy4RJBtkc
verbose: true
types:
  node:
    '*': '*'
  taxonomy_term:
    '*': '*'
types_translation_lock: {  }
form_op_lock:
  node:
    mode: 0
    values: {  }
  taxonomy_term:
    mode: 0
    values: {  }
timeout: null
