_core:
  default_config_hash: wNpilbhustdj8tLBsYJ6GPdxS5lUKU5rRei_XxSyd3A
google_map_api_key: AIzaSyAP9b78l95GF44gXjySpeNgXF1uPxtEFLg
google_map_api_server_key: AIzaSyCIG2yNomWI_kO9XgdXLYciaXkCEkVQr-Q
use_current_language: false
china_mode: false
google_maps_base_url: ''
google_map_custom_url_parameters:
  region: ''
  language: ''
  v: ''
  client: ''
  channel: ''
  libraries: {  }
