_core:
  default_config_hash: 7nVWnAgadYr2PZkqZ59A82npGM2K8XLEsn3e64dhr7g
langcode: en-gb
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en-gb: en-gb
    en: ''
  domains:
    en-gb: ''
selected_langcode: site_default
