_core:
  default_config_hash: UIIeh0uKSbu9MWfpNnlumkfllCLf0ylZJUXh7GfXWuU
langcode: en
entity_type_groups: {  }
separator: ''
tag_trim_method: beforeValue
use_maxlength: true
tag_trim_maxlength: {  }
tag_scroll_max_height: ''
tag_trim_end: '|.,-:;/+&([{"'''
