admin_content_links:
  moderated_content_disable: 1
  scheduled_content_disable: 1
view_overrides:
  all_drafts:
    filtered_node_types:
      application: 0
      contact: 0
      department_management: 0
      easychart: 0
      feature: 0
      featured_content_list: 0
      gallery: 0
      link: 0
      news: 0
      page: 0
      profile: 0
      publication: 0
      secure_market_statistics: 0
      secure_statistics: 0
      webform: 0
    disable: 0
  archived:
    filtered_node_types:
      application: 0
      contact: 0
      department_management: 0
      easychart: 0
      feature: 0
      featured_content_list: 0
      gallery: 0
      link: 0
      news: 0
      page: 0
      profile: 0
      publication: 0
      secure_market_statistics: 0
      secure_statistics: 0
      webform: 0
    disable: 0
  my_drafts:
    filtered_node_types:
      application: 0
      contact: 0
      department_management: 0
      easychart: 0
      feature: 0
      featured_content_list: 0
      gallery: 0
      link: 0
      news: 0
      page: 0
      profile: 0
      publication: 0
      secure_market_statistics: 0
      secure_statistics: 0
      webform: 0
    disable: 0
  needs_audit:
    filtered_node_types:
      application: 0
      contact: 0
      department_management: 0
      easychart: 0
      feature: 0
      featured_content_list: 0
      gallery: 0
      link: 0
      news: 0
      page: 0
      profile: 0
      publication: 0
      secure_market_statistics: 0
      secure_statistics: 0
      webform: 0
    disable: 1
  needs_review:
    filtered_node_types:
      application: 0
      contact: 0
      department_management: 0
      easychart: 0
      feature: 0
      featured_content_list: 0
      gallery: 0
      link: 0
      news: 0
      page: 0
      profile: 0
      publication: 0
      secure_market_statistics: 0
      secure_statistics: 0
      webform: 0
    disable: 0
