_core:
  default_config_hash: blfmQx2l-O0o6lCjybd2SQ2mMo0Qv7USRev0G4O--QE
mirror_operations:
  'view scheduled transition': update
  'add scheduled transition': update
  'reschedule scheduled transitions': update
automation:
  cron_create_queue_items: true
bundles:
  -
    entity_type: node
    bundle: application
  -
    entity_type: node
    bundle: contact
  -
    entity_type: node
    bundle: department_management
  -
    entity_type: node
    bundle: easychart
  -
    entity_type: node
    bundle: gallery
  -
    entity_type: node
    bundle: link
  -
    entity_type: node
    bundle: news
  -
    entity_type: node
    bundle: page
  -
    entity_type: node
    bundle: profile
  -
    entity_type: node
    bundle: publication
  -
    entity_type: node
    bundle: secure_market_statistics
  -
    entity_type: node
    bundle: secure_statistics
  -
    entity_type: node
    bundle: webform
  -
    entity_type: taxonomy_term
    bundle: site_topics
message_transition_latest: 'Scheduled transition: transitioning latest revision from [scheduled-transitions:from-state] to [scheduled-transitions:to-state]'
message_transition_historical: 'Scheduled transition: copied revision #[scheduled-transitions:from-revision-id] and changed from [scheduled-transitions:from-state] to [scheduled-transitions:to-state]'
message_transition_copy_latest_draft: 'Scheduled transition: reverted [scheduled-transitions:latest-state] revision #[scheduled-transitions:latest-revision-id] back to top'
message_override: false
