_core:
  default_config_hash: xNHQR5bN1V96bZQJu9E92f3VdiEMB8CHNkBOVTIlJmI
langcode: en
uuid: eab957f5-7ca4-4c91-b4cd-8768aad7f474
name: 'Northern Ireland Statistics and Research Agency'
mail: eddwebdev@finance-ni.gov.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
