_core:
  default_config_hash: Tjbqbv8qsEuiquVIg8iKEemwQEVbvDuqJZSr7yFndGk
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  admin_toolbar_tools__flush:
    weight: -99
    menu_name: admin
    parent: admin_toolbar_tools.help
    expanded: false
    enabled: true
  admin_toolbar_tools__plugin:
    weight: 1
    menu_name: admin
    parent: admin_toolbar_tools.flush
    expanded: false
    enabled: true
  admin_toolbar_tools__flush_rendercache:
    weight: 2
    menu_name: admin
    parent: admin_toolbar_tools.flush
    expanded: false
    enabled: true
  admin_toolbar_tools__flush_menu:
    weight: 3
    menu_name: admin
    parent: admin_toolbar_tools.flush
    expanded: false
    enabled: true
  admin_toolbar_tools__flush_static:
    weight: 4
    menu_name: admin
    parent: admin_toolbar_tools.flush
    expanded: false
    enabled: true
  admin_toolbar_tools__flush_twig:
    weight: 6
    menu_name: admin
    parent: admin_toolbar_tools.flush
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:flush_views':
    weight: 7
    menu_name: admin
    parent: admin_toolbar_tools.flush
    expanded: false
    enabled: true
  admin_toolbar_tools__theme_rebuild:
    weight: 8
    menu_name: admin
    parent: admin_toolbar_tools.flush
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:devel':
    weight: -98
    menu_name: admin
    parent: admin_toolbar_tools.help
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:devel__toolbar__settings':
    weight: 1
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:devel'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:devel__admin_settings':
    weight: 2
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:devel'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:devel__element_info':
    weight: 3
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:devel'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:devel__entity_info_page':
    weight: 5
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:devel'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:devel__menu_rebuild':
    weight: 6
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:devel'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:devel__reinstall':
    weight: 7
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:devel'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:devel__session':
    weight: 8
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:devel'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:devel__state_system_page':
    weight: 9
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:devel'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:devel__theme_registry':
    weight: 10
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:devel'
    expanded: false
    enabled: true
  system__run_cron:
    weight: -97
    menu_name: admin
    parent: admin_toolbar_tools.help
    expanded: false
    enabled: true
  system__db_update:
    weight: -96
    menu_name: admin
    parent: admin_toolbar_tools.help
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:user__logout':
    weight: -94
    menu_name: admin
    parent: admin_toolbar_tools.help
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__alert':
    weight: -95
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__application':
    weight: -94
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__article':
    weight: -93
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__consultation':
    weight: -92
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__contact':
    weight: -91
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__department_management':
    weight: -90
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__feature':
    weight: -89
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__featured_content_list':
    weight: -88
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__link':
    weight: -87
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__news':
    weight: -86
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__page':
    weight: -85
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__profile':
    weight: -83
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__publication':
    weight: -82
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__webform':
    weight: -81
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:view__files':
    weight: 4
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:media_page':
    weight: 6
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
  entity__scheduled_transition__collection:
    weight: 7
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
