_core:
  default_config_hash: Tjbqbv8qsEuiquVIg8iKEemwQEVbvDuqJZSr7yFndGk
langcode: en
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
