features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
social_links_twitter: 'https://x.com/Hsenigov'
social_links_facebook: 'https://www.facebook.com/hseni.gov.uk'
social_links_youtube: 'https://www.youtube.com/user/HSENIvideo'
social_links_instagram: 'https://www.instagram.com/hseni.gov.uk/'
social_links_linkedin: 'https://uk.linkedin.com/company/health-and-safety-executive-for-northern-ireland'
social_links_rss: ''
