<?php

/**
 * @file
 * Common overrides and preprocessing.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form.
 *
 * Completely hide the Meta vertical tab (field group) from people without permission.
 *
 */
function corplite_common_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // If the current user has the permission, do not hide the Meta vertical tab.
  $x = 1;
  if (\Drupal::currentUser()->hasPermission('hide topic or feature on homepage')) {
    return;
  }
  else {
    $form['field_feature_home_page']['#access'] = FALSE;
    $form['field_main_feature']['#access'] = FALSE;
    $form['field_hide_topic']['#access'] = FALSE;
  }
}
