adding:
  dependencies:
    config:
      - search_api_solr.solr_field_type.text_edge_und_6_0_0
      - search_api_solr.solr_field_type.text_en_6_0_0
      - search_api_solr.solr_field_type.text_ngram_und_6_0_0
      - search_api_solr.solr_field_type.text_string_und_6_0_0
      - search_api_solr.solr_field_type.text_und_6_0_0
  name: 'NISRA search'
  backend_config:
    connector_config:
      host: nisra_solr
      port: 8983
removing:
  dependencies:
    config:
      - search_api_solr.solr_field_type.text_edge_und_7_0_0
      - search_api_solr.solr_field_type.text_en_7_0_0
      - search_api_solr.solr_field_type.text_ngram_und_7_0_0
      - search_api_solr.solr_field_type.text_und_7_0_0
  name: Default
  backend_config:
    connector_config:
      host: solr.internal
      port: 8080
