project_type: corp-lite
project_name: 'Corp Lite'
project_id: 5wphupyrfaitk
project_disk_size: 3000
db_disk_size: 1000
sites:
    nisra:
        name: nisra
        url: nisra.gov.uk
        solr: nisra
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/nisra ; drush core-cron'
        database: nisra
        status: development
        default: true
    afbini:
        name: afbini
        url: afbini.gov.uk
        solr: afbini
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/afbini ; drush core-cron'
        database: afbini
        status: development
        default: false
    hse:
        name: 'Health and Safety Executive'
        url: hse.gov.uk
        solr: hse
        www: true
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/hse ; drush core-cron'
        database: hse
        status: development
        default: false
