project_type: corp-lite
project_name: 'Corp Lite'
project_id: 5wphupyrfaitk
project_disk_size: 34816
db_disk_size: 12288
sites:
    nisra:
        name: nisra
        url: nisra.gov.uk
        solr: nisra
        www: true
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/nisra ; drush core-cron'
        database: nisra
        status: production
        default: true
    afbini:
        name: afbini
        url: afbini.gov.uk
        solr: afbini
        www: true
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/afbini ; drush core-cron'
        database: afbini
        status: production
        default: false
    hseni:
        name: hseni
        url: hseni.gov.uk
        solr: hseni
        www: true
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/hseni ; drush core-cron'
        database: hseni
        status: production
        default: false
    etini:
        name: 'Education Training Inspectorate NI'
        url: etini.gov.uk
        solr: etini
        www: true
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/etini ; drush core-cron'
        database: etini
        status: production
        default: false
    northsouthministerialcouncil:
        name: 'North South Ministerial Council'
        url: northsouthministerialcouncil.org
        solr: northsouthministerialcouncil
        www: true
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/northsouthministerialcouncil ; drush core-cron'
        database: northsouthministerialcouncil
        status: development
        default: false
