features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
social_links_twitter: 'https://x.com/ETI_news'
social_links_facebook: 'https://www.facebook.com/ETInews'
social_links_youtube: ''
social_links_instagram: ''
social_links_linkedin: ''
social_links_rss: ''
