_core:
  default_config_hash: d1uMRwYRLT0cN9E8b2nawivRZKPsP2fe9yUuzjQNvuI
langcode: en-gb
description:
  type: textfield
  length: 128
icon:
  directory: core/modules/file/icons
make_unused_managed_files_temporary: false
