_core:
  default_config_hash: 93THGI2m_bLRVSkcQ82oEbDdzS6dUZMZ0ObOX_D_bQ0
langcode: en
description:
  type: textfield
  length: 128
icon:
  directory: core/modules/file/icons
make_unused_managed_files_temporary: false
