_core:
  default_config_hash: 7nVWnAgadYr2PZkqZ59A82npGM2K8XLEsn3e64dhr7g
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en-gb: ''
  domains:
    en-gb: ''
selected_langcode: site_default
