_core:
  default_config_hash: evTtv-kgq7FngYj6EJShrrnvfKzLr0QQRBc9LP6fUS4
map:
  'no': nb
  pt: pt-pt
  zh: zh-hans
  zh-tw: zh-hant
  zh-hk: zh-hant
  zh-mo: zh-hant
  zh-cht: zh-hant
  zh-cn: zh-hans
  zh-sg: zh-hans
  zh-chs: zh-hans
