_core:
  default_config_hash: FGko595Zb7qzmehyqDvpydOOJWwKuQoNs9gGBjQ3KLw
langcode: en
entity_type_groups: {  }
separator: ''
tag_trim_method: beforeValue
use_maxlength: true
tag_trim_maxlength: {  }
tag_scroll_max_height: ''
