_core:
  default_config_hash: mzc1pg77k9uDCQxVAGMq0h63KtrQ1HanPgV5nrOIo7Q
langcode: en
auto_redirect: true
default_status_code: 301
passthrough_querystring: true
warning: false
ignore_admin_path: false
access_check: false
route_normalizer_enabled: true
