_core:
  default_config_hash: g0RQHDSROpju3b5Vfd-DqtO6YaMPhBHB2hY5xidOObc
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: ''
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
