_core:
  default_config_hash: aPd4aZdCN7jO7hxaZlpmOeO4fE31KA-ApmC9QLIiFkY
langcode: en
uuid: a21b5962-5a95-473f-b866-742f9ac07bb2
name: 'North South Ministerial Council'
mail: admin@northsouthministerialcouncil.org
slogan: ''
page:
  403: ''
  404: ''
  front: /
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
