_core:
  default_config_hash: dDj8PAQ5aPEWdPiAyLJcju-2Cces8F3FLGmlXW6aVCo
langcode: en
first_day: 0
country:
  default: GB
timezone:
  default: Europe/London
  user:
    configurable: true
    default: 0
    warn: false
