_core:
  default_config_hash: j0jq8lpOtkBGY9Fcfeu63MAt9Q5HzEekujJrSDkqT9w
langcode: en
check:
  disabled_extensions: false
  interval_days: 1
fetch:
  url: ''
  max_attempts: 2
  timeout: 30
notification:
  emails:
    - admin@northsouthministerialcouncil.org
  threshold: all
