_core:
  default_config_hash: ekTrW42fCUKO9lbwqDQmRp-Tg1XF97I6ZnnMS4P1TyM
langcode: en-gb
check:
  disabled_extensions: false
  interval_days: 1
fetch:
  url: ''
  max_attempts: 2
  timeout: 30
notification:
  emails:
    - admin@northsouthministerialcouncil.org
  threshold: all
