_core:
  default_config_hash: roSXtKUc9dGq1SWH5jla1hNyFoChGsOGNIgk0fZ7_O8
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en-gb: ''
    en: ''
  domains:
    en-gb: ''
selected_langcode: site_default
