#############################################################################
###                           --== IMPORTANT ==--                         ###
#############################################################################
# If you require changes to this file you must edit the file within the     #
# original repository.Any changes here will be overwritten when the project #
# is built.                                                                 #
#############################################################################
'https://www.nisra.gov.uk.{default}/':
    type: upstream
    upstream: 'corp_lite:http'
    cache:
        enabled: 'false'
'https://nisra.gov.uk.{default}/':
    type: redirect
    to: 'https://www.nisra.gov.uk.{default}/'
'https://www.afbini.gov.uk/':
    type: upstream
    upstream: 'corp_lite:http'
    cache:
        enabled: 'false'
'https://afbini.gov.uk/':
    type: redirect
    to: 'https://www.afbini.gov.uk/'
'https://www.hseni.gov.uk/':
    type: upstream
    upstream: 'corp_lite:http'
    cache:
        enabled: 'false'
'https://hseni.gov.uk/':
    type: redirect
    to: 'https://www.hseni.gov.uk/'
'https://www.etini.gov.uk/':
    type: upstream
    upstream: 'corp_lite:http'
    cache:
        enabled: 'false'
'https://etini.gov.uk/':
    type: redirect
    to: 'https://www.etini.gov.uk/'
'https://www.{all}/':
    type: upstream
    upstream: 'corp_lite:http'
    cache:
        enabled: 'false'
'https://{all}/':
    type: redirect
    to: 'https://www.{all}/'
