#############################################################################
###                           --== IMPORTANT ==--                         ###
#############################################################################
# If you require changes to this file you must edit the file within the     #
# original repository.Any changes here will be overwritten when the project #
# is built.                                                                 #
#############################################################################
db:
    type: 'mariadb:10.4'
    disk: 1000
    configuration:
        schemas:
            - nisradb
            - afbinidb
            - hsenidb
            - etinidb
        endpoints:
            nisra:
                default_schema: nisradb
                privileges:
                    nisradb: admin
            afbini:
                default_schema: afbinidb
                privileges:
                    afbinidb: admin
            hseni:
                default_schema: hsenidb
                privileges:
                    hsenidb: admin
            etini:
                default_schema: etinidb
                privileges:
                    etinidb: admin
solr_8_11:
    type: 'solr:8.11'
    disk: 1024
    configuration:
        cores:
            nisra_index:
                conf_dir: !archive solr_config/
            afbini_index:
                conf_dir: !archive solr_config/
            hseni_index:
                conf_dir: !archive solr_config/
            etini_index:
                conf_dir: !archive solr_config/
        endpoints:
            nisra:
                core: nisra_index
            afbini:
                core: afbini_index
            hseni:
                core: hseni_index
            etini:
                core: etini_index
redis:
    type: 'redis:6.0'
