<?php

declare(strict_types=1);

/**
 * @file
 * Code to provide District Inspectors search facility.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function etini_district_inspectors_theme(): array {
  return [
    'school' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for school templates.
 *
 * Default template: school.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the school information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_school(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_form_alter().
 */
function etini_district_inspectors_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add autocomplete processing to the exposed filter on the District Inspectors view.
  if (($form_id == 'views_exposed_form') && ($form['#action'] == '/district-inspectors')) {
    $form['search_api_fulltext']['#autocomplete_route_name'] = 'inspector.autocomplete';
    $form['#attached']['library'][] = 'etini_district_inspectors/auto_submit';
  }
}
