<?php

/**
 * @file
 * Primary module hooks for Nisra common module.
 */

use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityStorageInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Language\Language;
use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\StreamWrapper\StreamWrapperManager;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\Url;
use Drupal\node\Entity\Node;
use Drupal\redirect\Entity\Redirect;
use Drupal\taxonomy\TermInterface;
use Drupal\views\Plugin\views\cache\CachePluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function nisra_common_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\Core\Entity\EntityFormInterface $form_object */
  $form_object = $form_state->getFormObject();
  /** @var \Drupal\node\NodeInterface $node */
  $node = $form_object->getEntity();

  if ($node->bundle() === 'secure_market_statistics' || $node->bundle() === 'secure_statistics') {
    $form['#validate'][] = 'nisra_common_validate_secure_attachment';
  }

  if ($node->bundle() === 'publication') {
    $form['#validate'][] = 'nisra_common_validate_attachment';
  }
}

/**
 * Form validation callback.
 */
function nisra_common_validate_secure_attachment(&$form, FormStateInterface $form_state) {
  $values = $form_state->getValues();

  // Validate file attachments and external links.
  if (empty($values['field_secure_attachment']["selection"][0]) && empty($values['field_external_publication'][0]['uri'])) {
    $form_state->setErrorByName('field_secure_attachment', t('You must provide an attachment or external link'));
    $form_state->setErrorByName('field_external_publication', t('You must provide an attachment or external link'));
  }
}

/**
 * Form validation callback.
 */
function nisra_common_validate_attachment(&$form, FormStateInterface $form_state) {
  $values = $form_state->getValues();

  // Validate file attachments and external links.
  if (empty($values['field_attachment']["selection"][0]) && empty($values['field_external_publication'][0]['uri'])) {
    $form_state->setErrorByName('field_attachment', t('You must provide an attachment or external link'));
    $form_state->setErrorByName('field_external_publication', t('You must provide an attachment or external link'));
  }
}

/**
 * Implements hook_preprocess_HOOK() for fieldset.
 */
function nisra_common_preprocess_fieldset(&$variables) {
  $element = &$variables['element'];
  if ($element['#id'] == 'group-publications') {
    $variables['legend_span']['attributes']['class'][] = 'js-form-required form-required';
  }
}

/**
 * Implements hook_file_download().
 */
function nisra_common_file_download($uri) {
  // Check if the file is coming from the private stream wrapper, these are
  // the only ones that we want to check.
  if (StreamWrapperManager::getScheme($uri) == 'private') {
    // Get the file record based on the URI. If not in the database just return.
    $file_repository = \Drupal::service('file.repository');
    $file = $file_repository->loadByUri($uri);
    if (!$file) {
      return;
    }

    // Identify the media that is being downloaded
    $database = \Drupal::database();
    $references = file_get_file_references($file, NULL, EntityStorageInterface::FIELD_LOAD_CURRENT, NULL);
    foreach ($references as $field) {
      if (isset($field['media'])) {
        // Retrieve the media ids (mids).
        $mids = array_keys($field['media']);
        foreach ($mids as $mid) {
          if (!check_media_access($database, $mid)) {
            return -1;
          }
        }
      }
    }
  }

  return NULL;
}

/**
 * Check access for this media id (mid).
 */
function check_media_access($database, $mid) {
  // Find all nodes of type 'Secure Statistics' or
  // 'Secure - market sensitive statistics' that this media item is attached to.
  $query = $database->query("select entity_id, bundle
                        from node__field_secure_attachment
                        where bundle in ('secure_statistics','secure_market_statistics' )
                        and field_secure_attachment_target_id = :mid", [':mid' => $mid]);
  $result = $query->fetchAll();
  // Loop through all nodes, if the current user is denied access on one,
  // then they are denied on all !
  foreach ($result as $entity) {
    // Load up the entity/node.
    $node = Node::load($entity->entity_id);
    if (!empty($node)) {
      // If the entity is published then allow access and don't bother
      // with any more checks.
      if (!$node->isPublished()) {
        if (Drupal::currentUser()->isAnonymous()) {
          // If this is an anonymous user then deny access.
          \Drupal::logger('nisra_common')
            ->notice(t("Denying anonymous user access to mid " .
              $mid . " in nisra_common_file_download() function"));
          return FALSE;
        }
        else {
          // This is a logged in user so we need to check permissions.
          // Permissions that we are looking for are
          // 'view secure_market_statistics revisions' or
          // 'view secure_statistics revision'
          if (!\Drupal::currentUser()
            ->hasPermission('view ' . $entity->bundle . ' revisions')) {
            // User does not have permission, deny access.
            \Drupal::logger('nisra_common')->notice(t("Denying user " .
              \Drupal::currentUser()->id() . " access to mid " .
              $mid . " due to insufficient permissions in nisra_common_file_download() function"));
            return FALSE;
          }
        }
      }
    }
  }
  return TRUE;
}

/**
 * Implements template_preprocess_views_view_table()
 *
 * @param $variables
 */
function nisra_common_preprocess_views_view_table(&$variables) {
  /** @var ViewExecutable $view */
  $view = $variables['view'];

  //Only alter admin/content view
  if ($view->id() !== 'content' && $view->id() !== 'workflow_moderation') {
    return;
  }
  $rows = $variables['rows'];
  foreach ($rows as $key => $row) {
    if (preg_match('/market sensitive/', $row['columns']['type']['content'][0]['field_output']['#markup']) && preg_match('/Unpublished/', $row['columns']['status']['content'][0]['field_output']['#markup'])) {
      if (!\Drupal::currentUser()
        ->hasPermission('edit any secure_market_statistics content')) {
        unset($variables['rows'][$key]);
      }
    }
    if (preg_match('/Secure statistics/', $row['columns']['type']['content'][0]['field_output']['#markup']) && preg_match('/Unpublished/', $row['columns']['status']['content'][0]['field_output']['#markup'])) {
      if (!\Drupal::currentUser()
        ->hasPermission('edit any secure_statistics content')) {
        unset($variables['rows'][$key]);
      }
    }
  }
}

/**
 * Implements hook_system_breadcrumb_alter().
 *
 */
function nisra_common_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  $route_name = $route_match->getRouteName();
  $links = $breadcrumb->getLinks();
  $breadcrumb = new Breadcrumb();
  if ($route_name === 'entity.taxonomy_term.canonical') {

    $new_links[] = Link::createFromRoute('Home', '<front>');
    $new_links[] = Link::fromTextAndUrl('Statistics and Research', Url::fromUri('internal:/Statistics'));

    array_shift($links);
    $links = array_merge($new_links, $links);
    $breadcrumb->setLinks($links);
    $breadcrumb->addCacheContexts(['url.path']);
  }
}

/**
 * Implements hook_entity_presave().
 *
 * Automatically sets 'Publication Rating' on relevant content types
 * based on the linked Publication Series tag.
 */
function nisra_common_entity_presave(\Drupal\Core\Entity\EntityInterface $entity) {

  $content_types = [
    'publication',
    'secure_market_statistics',
    'secure_statistics',
  ];

  if ($entity instanceof \Drupal\node\Entity\Node && in_array($entity->bundle(), $content_types)) {

    if ($entity->hasField('field_publication_series') && $entity->hasField('field_publication_rating')) {

      // Only set if the field is empty
      if ($entity->get('field_publication_rating')->isEmpty()) {

        $series_term = $entity->get('field_publication_series')->entity;

        if ($series_term && $series_term->hasField('field_document_type') && !$series_term->get('field_document_type')->isEmpty()) {

          $doc_type_tid = $series_term->get('field_document_type')->target_id;

          $entity->set('field_publication_rating', [
            'target_id' => $doc_type_tid,
          ]);
        }
      }
    }
  }
}

/**
 * Implements hook_entity_view().
 *
 * Adds a message on publication nodes indicating whether this is the latest
 * release in the series or not.
 */
function nisra_common_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {

  // Only for the content types that have publication series field
  $types = ['publication', 'secure_market_statistics', 'secure_statistics'];

  if ($entity instanceof Node && in_array($entity->bundle(), $types) && $view_mode === 'full') {

    // Make sure the publication is tagged to a series
    if (!$entity->get('field_publication_series')->isEmpty()) {
      $series = $entity->get('field_publication_series')->entity;

      if ($series) {

        // Get all published nodes in the same series
        $query = \Drupal::entityTypeManager()->getStorage('node')->getQuery();
        $nids = $query
          ->accessCheck(TRUE)
          ->condition('status', 1) // published only
          ->condition('field_publication_series.target_id', $series->id())
          ->condition('type', $types, 'IN')
          ->sort('field_published_date', 'DESC') // Sorting by published date in descending order
          ->execute();

        if (!empty($nids)) {
          $latest_nid = reset($nids); // first node is the newest

          if ($latest_nid == $entity->id()) {
            // This node is the latest in the series
            $link = Url::fromUri('internal:/publications/series/' . $series->id())->toString();
            $message_markup = 'This is the latest release in this series. <a href="' . $link . '">View previous releases.</a>';
          }
          else {
            // This node is not the latest in the series
            $link = Url::fromRoute('entity.node.canonical', ['node' => $latest_nid])->toString();
            $message_markup = 'This is not the latest release in this series. <a href="' . $link . '">View the latest release.</a>';
          }

          // Add the message below meta fields
          $build['latest_in_series_message'] = [
            '#type' => 'container',
            '#attributes' => ['class' => ['latest-message']],
            'markup' => [
              '#type' => 'markup',
              '#markup' => $message_markup,
              '#allowed_tags' => ['a'],
            ],
            '#weight' => 4,
          ];
        }
      }
    }
  }
}

/**
 * Implements hook_taxonomy_term_insert().
 */
function nisra_common_taxonomy_term_insert(TermInterface $term) {
  // Only apply to a specific vocabulary.
  if ($term->bundle() !== 'publication_series') {
    return;
  }
  // Create a redirect from the taxonomy term when a landing page is created
  // if a subtheme has been selected and the node is published.
  if ($term->isPublished()) {
    nisra_common_create_publication_series_to_site_topic_redirect($term);
  }
}

/**
 * Implements hook_taxonomy_term_update().
 */
function nisra_common_taxonomy_term_update(TermInterface $term) {
  if ($term->bundle() !== 'publication_series') {
    return;
  }
  // Update theme redirect when default revision is published or
  // remove the theme redirect if (not published and) it is a default revision.
    if ($term->isPublished()) {
      // Update is publishing the page - remove and re-create theme redirect.
      nisra_common_delete_publication_series_to_site_topic_redirect($term->original);
      nisra_common_create_publication_series_to_site_topic_redirect($term);
    }
    elseif ($term->isDefaultRevision()) {
      // Un-published default revision - remove theme redirect.
      nisra_common_create_publication_series_to_site_topic_redirect($term->original);
    }
}

/**
 * Landing page checks.
 *
 * - Whether there is already a landing page associated with the theme selected.
 * - Create a redirect or warn user if there is a landing page for this theme.
 *
 * @param \Drupal\taxonomy\Entity\Term $term
 *   The landing page node entity.
 */
function nisra_common_create_publication_series_to_site_topic_redirect(EntityInterface $term) {
  /** @var \Drupal\taxonomy\Entity\Term $term */
  // Determine the theme path that will be the redirect source.
  $site_topic_tid = $term->get('field_site_topics')->getString();
  $taxonomy_term_path = 'taxonomy/term/' . $site_topic_tid;

  // Create a theme redirect if there is no existing redirect
  // where the theme path is the redirect source.
  $redirect_url = nisra_common_get_redirect_url($taxonomy_term_path);
  if (empty($redirect_url)) {
    Redirect::create([
      'redirect_source' => [
        'path' => $taxonomy_term_path,
        'query' => [],
      ],
      'redirect_redirect' => [
        'uri' => 'internal:/taxonomy/term/' . $term->id(),
      ],
      'language' => Language::LANGCODE_NOT_SPECIFIED,
      'status_code' => '301',
    ])->save();
  }
  else {
    // Just check that the existing redirect is not for the current node.
    $current_node = \Drupal::routeMatch()->getParameter('node');
    if (!empty($current_node)) {
      $this_alias = \Drupal::service('path_alias.manager')->getAliasByPath('/taxonomy/term/' . $current_node->id());
      if ($this_alias == $redirect_url) {
        // Redirect is for the current node, do not error.
        return;
      }
    }

    // Notify the user that a redirect could not be created.
    \Drupal::messenger()->addWarning(t('A redirect from the theme taxonomy page to this content was not created,
        because there are already one or more redirects used for the theme taxonomy page.'));

    // Add a convenience link for users who can administer redirects.
    if (\Drupal::currentUser()->hasPermission('administer redirects')) {
      $link = Link::createFromRoute('review existing redirects', 'redirect.list', [], [
        'query' => ['text' => $taxonomy_term_path],
      ])->toString();

      \Drupal::messenger()->addWarning(new TranslatableMarkup(
          "You can @link to remove any unwanted redirects.", ["@link" => $link])
      );
    }
  }
}

/**
 * Detect whether a redirect already exists.
 *
 * @param string $source_path
 *   The source path.
 *
 * @return string
 *   Redirect URL if found, empty string if not.
 */
function nisra_common_get_redirect_url(string $source_path) {
  $redirect = \Drupal::service('redirect.repository')->findBySourcePath($source_path);
  $redirect_url = '';

  if (!empty(($redirect))) {
    $redirect = array_pop($redirect);
    $redirect_url = $redirect->getRedirectUrl()->toString();
  }

  return $redirect_url;
}

/**
 * Deletes a theme to landing page redirect.
 *
 * @param \Drupal\taxonomy\Entity\Term $term
 *   The landing page node.
 */
function nisra_common_delete_publication_series_to_site_topic_redirect(EntityInterface $term) {
  /** @var \Drupal\taxonomy\Entity\Term $term */

  $redirect_repository = \Drupal::service('redirect.repository');

  // The redirect to delete must have a source path that matches
  // the path of the theme taxonomy term for the landing page and
  // a destination path that matches the landing page node path.
  $site_topic_tid = $term->get('field_site_topics')->getString();
  $source_path = '/taxonomy/term/' . $site_topic_tid;
  $destination_path[] = 'internal:/taxonomy/term/' . $term->id();

  // Get all redirects whose destination is the landing page.
  $redirects = $redirect_repository->findByDestinationUri($destination_path);
  foreach ($redirects as $redirect) {
    // Delete the redirect if its source is landing page theme path.
    if ($redirect->getSourceUrl() == $source_path) {
      $redirect->delete();
    }
  }
}
